CREATE TABLE account (
id BIGSERIAL PRIMARY KEY,
client_id VARCHAR(12) NOT NULL,
product_id BIGINT NOT NULL,
balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
interest_rate DECIMAL(5, 2),
is_recalc BOOLEAN NOT NULL DEFAULT FALSE,
card_exist BOOLEAN NOT NULL DEFAULT FALSE,
status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CLOSED', 'BLOCKED', 'ARRESTED'))
);

